export const accountType = {
    "Alpari-mt5-demo":{
        value:"Alpari-mt5-demo",
        text:"Alpari-mt5-demo"
    },
    "Alpari-pro-ECN-Demo":{
        value:"Alpari-pro-ECN-Demo",
        text:"Alpari-pro-ECN-Demo"
    },
    "RoboForex-ECN":{
        value:"RoboForex-ECN",
        text:"RoboForex-ECN"
    },
    "Roboforex-Demo":{
        value:"Roboforex-Demo",
        text:"Roboforex-Demo"
    },
    "Amarkets-Demo":{
        value:"Amarkets-Demo",
        text:"Amarkets-Demo"
    },

    "ICMarketsSC-Demo02":{
        value:"ICMarketsSC-Demo02",
        text:"ICMarketsSC-Demo02"
    },
    "ICMarketsSC-Demo03":{
        value:"ICMarketsSC-Demo03",
        text:"ICMarketsSC-Demo03"
    },
    "ICMarketsSC-Demo01":{
        value:"ICMarketsSC-Demo01",
        text:"ICMarketsSC-Demo01"
    },
    "ICMarketsSC-Demo04":{
        value:"ICMarketsSC-Demo04",
        text:"ICMarketsSC-Demo04"
    },
    "TCBridge-Demo":{
        value:"TCBridge-Demo",
        text:"TCBridge-Demo"
    },
    
    "ICMarketsSC-Demo":{
        value:"ICMarketsSC-Demo",
        text:"ICMarketsSC-Demo"
    },
    "ICMarketsSC-Demo05":{
        value:"ICMarketsSC-Demo05",
        text:"ICMarketsSC-Demo05"
    },
    "ICMarketsSC-Demo06":{
        value:"ICMarketsSC-Demo06",
        text:"ICMarketsSC-Demo06"
    },
    "doesNotExist":{
        value:"doesNotExist",
        text:"پلتفرم بین گزینه های موجود یافت نشد"
    },
    "none":{
        value:"none",
        text:"هیچکدام"
    }
}

export const maxLossLimit = {
    8:8,
    10:10,
    12:12
}

export const accountLevels = {
    1:{
        infinitive:false,
        percentDays:8,
        maxTradeDays:30,
        level:1,
    },
    2:{
        infinitive:false,
        percentDays:4,
        maxTradeDays:60,
        level:2,
    },
    3:{
        infinitive:true,
        percentDays:0,
        maxTradeDays:0,
        level:3,
    }
}